-- Insert 10 sample blog posts
INSERT INTO BlogPost (id, title, slug, excerpt, content, thumbnail, isPublished, publishedAt, metaTitle, metaDescription, metaKeywords, createdAt, updatedAt) VALUES
('blog-1', 'AI trong Giáo dục: Xu hướng 2026 và Tương lai', 'ai-trong-giao-duc-xu-huong-2026', 'Khám phá cách AI đang thay đổi ngành giáo dục, từ học tập cá nhân hóa đến đánh giá tự động.', '<h2>AI đang cách mạng hóa giáo dục</h2><p>Trí tuệ nhân tạo không còn là khái niệm xa vời mà đã trở thành một phần không thể thiếu trong lĩnh vực giáo dục.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800', 1, datetime('now'), 'AI trong Giáo dục 2026 | The Tulie Lab', 'Khám phá cách AI đang thay đổi ngành giáo dục với học tập cá nhân hóa', 'AI giáo dục, trí tuệ nhân tạo', datetime('now'), datetime('now')),

('blog-2', 'Vibe Coding là gì? Hướng dẫn từ A-Z cho người mới bắt đầu', 'vibe-coding-la-gi-huong-dan-a-z', 'Tìm hiểu về Vibe Coding - phương pháp lập trình mới với sự hỗ trợ của AI.', '<h2>Vibe Coding - Lập trình thời AI</h2><p>Vibe Coding là khái niệm mới mô tả cách tiếp cận lập trình với sự hỗ trợ mạnh mẽ từ AI.</p>', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800', 1, datetime('now'), 'Vibe Coding là gì? | The Tulie Lab', 'Vibe Coding là phương pháp lập trình mới với AI', 'vibe coding, AI coding', datetime('now'), datetime('now')),

('blog-3', 'Xây dựng MVP trong 2 tuần: Case Study thực tế', 'xay-dung-mvp-trong-2-tuan-case-study', 'Câu chuyện thực tế về việc xây dựng một sản phẩm MVP hoàn chỉnh trong 2 tuần.', '<h2>Từ ý tưởng đến sản phẩm trong 14 ngày</h2><p>Đây là câu chuyện về cách chúng tôi đã xây dựng một ứng dụng quản lý dự án MVP.</p>', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800', 1, datetime('now'), 'Xây dựng MVP trong 2 tuần | The Tulie Lab', 'Case study thực tế về xây dựng MVP', 'MVP, startup, case study', datetime('now'), datetime('now')),

('blog-4', 'Top 10 công cụ No-Code/Low-Code 2026', 'top-10-cong-cu-no-code-low-code-2026', 'Danh sách các công cụ No-Code và Low-Code tốt nhất năm 2026.', '<h2>Công cụ No-Code/Low-Code hàng đầu</h2><p>Năm 2026 chứng kiến sự bùng nổ của các công cụ giúp bạn xây dựng ứng dụng mà không cần viết code.</p>', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800', 1, datetime('now'), 'Top 10 No-Code 2026 | The Tulie Lab', 'Danh sách 10 công cụ No-Code tốt nhất', 'no-code, low-code, bubble', datetime('now'), datetime('now')),

('blog-5', 'Tại sao TypeScript là lựa chọn số 1 cho dự án mới?', 'tai-sao-typescript-lua-chon-so-1', 'Phân tích lý do TypeScript đang thống trị thế giới JavaScript.', '<h2>TypeScript: JavaScript với superpowers</h2><p>TypeScript không chỉ là JavaScript có kiểu dữ liệu. Nó là một công cụ giúp bạn viết code tốt hơn.</p>', 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=800', 1, datetime('now'), 'Tại sao TypeScript số 1 | The Tulie Lab', 'Phân tích lý do TypeScript đang thống trị', 'typescript, javascript', datetime('now'), datetime('now')),

('blog-6', 'Hướng dẫn Deploy Next.js lên Vercel từ A-Z', 'huong-dan-deploy-nextjs-vercel', 'Hướng dẫn chi tiết cách deploy ứng dụng Next.js lên Vercel miễn phí.', '<h2>Deploy Next.js lên Vercel</h2><p>Vercel là nền tảng tốt nhất để deploy Next.js vì nó được tạo ra bởi cùng team.</p>', 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=800', 1, datetime('now'), 'Deploy Next.js lên Vercel | The Tulie Lab', 'Hướng dẫn deploy Next.js lên Vercel', 'nextjs, vercel, deploy', datetime('now'), datetime('now')),

('blog-7', 'Prisma vs TypeORM: So sánh chi tiết 2026', 'prisma-vs-typeorm-so-sanh-2026', 'So sánh hai ORM phổ biến nhất cho Node.js: Prisma và TypeORM.', '<h2>Prisma vs TypeORM</h2><p>Cả hai đều là những ORM tuyệt vời, nhưng có những khác biệt quan trọng.</p>', 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?q=80&w=800', 1, datetime('now'), 'Prisma vs TypeORM 2026 | The Tulie Lab', 'So sánh Prisma và TypeORM', 'prisma, typeorm, orm', datetime('now'), datetime('now')),

('blog-8', '5 Sai lầm phổ biến khi học lập trình', '5-sai-lam-pho-bien-khi-hoc-lap-trinh', 'Những sai lầm thường gặp khi bắt đầu học code và cách tránh.', '<h2>Sai lầm khi học lập trình</h2><p>Học quá nhiều ngôn ngữ cùng lúc, không thực hành đủ, copy paste không hiểu.</p>', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=800', 1, datetime('now'), '5 Sai lầm khi học code | The Tulie Lab', 'Những sai lầm phổ biến của người mới học', 'học lập trình, tips', datetime('now'), datetime('now')),

('blog-9', 'Thiết kế Database Schema: Best Practices', 'thiet-ke-database-schema-best-practices', 'Hướng dẫn thiết kế database schema hiệu quả, tối ưu performance.', '<h2>Database Schema Design</h2><p>Normalization, naming conventions, indexes, foreign keys, soft delete.</p>', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800', 1, datetime('now'), 'Database Schema Best Practices | The Tulie Lab', 'Hướng dẫn thiết kế database schema', 'database, schema, sql', datetime('now'), datetime('now')),

('blog-10', 'Authentication với JWT: Hướng dẫn bảo mật', 'authentication-jwt-huong-dan-bao-mat', 'Hướng dẫn implement JWT authentication an toàn.', '<h2>JWT Authentication</h2><p>JSON Web Tokens là standard phổ biến cho authentication. Best practices và bảo mật.</p>', 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=800', 1, datetime('now'), 'JWT Authentication | The Tulie Lab', 'Implement JWT authentication an toàn', 'jwt, authentication, bảo mật', datetime('now'), datetime('now'));
